# Generated by Django 3.2.5 on 2021-10-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserOne',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='UserTwo',
        ),
    ]
